### ISSUE TITLE
As visitor I want to create a shared room So that I can send the link to my team members

### ISSUE THREAD

**Issue by GustaSilvaBr** [GustavoSilva-hub/moveit-in-team#1]
### Description
Create a shared room generating a access code to anothers members enter in the room. After the creation, the Visitor can go to the shared room by the "go" buttom.

### Tasks

- [ ] Configure noSQL database
- [ ] Define necessary collections and the attributes
- [ ] Create a Shared room with randomic code as key (3 is the max)
- [ ] Load room document when the shared room is access with an existing code
- [ ] Foreach visitor access add a team member in the shared room (4 is the max)
